### ISSUE TITLE
Failed Functional Testing 

### ISSUE THREAD

**Issue by mle6366** [ExpanseLLC/lambda_authorizer#1]
Wed Sep 14 21:16:33 UTC 2016 : Authorizer result body before parsing: null
Wed Sep 14 21:16:33 UTC 2016 : Execution failed due to configuration error: Could not parse policy
Wed Sep 14 21:16:33 UTC 2016 : AuthorizerConfigurationException

**Comment by mfisher29** [comment]
Hi, wondering how you fixed this issue. Having the same three error messages!

**Comment by mle6366** [comment]
@mfisher29 Hey, this was caused when the invoker (in this case apigateway) expected a returned policy document but (erroneousy) received null. Just make sure you're actually returning the policy document+principald from your lambda function.

**Comment by mfisher29** [comment]
That was it, thank you! @mle6366
