### ISSUE TITLE
Custom Lambda Authorizer - Amazon Identity Provider Configuration for Expanse LLC

### ISSUE THREAD

**Issue by mle6366** [ExpanseLLC/lambda_authorizer#4]
Token retrieved from Amazon ID Provider needs to be verified by the Lambda Authorizer and the principalId returned.

AmznIdModule.js returns a 0 or a principalId to the AuthorizerModule.js class

**Comment by ryanwscott** [comment]
@mle6366 I started looking into this. Amazon requires a privacy policy that they will display when a user clicks the login with amazon button. We need that before we can start this.

[Login with Amazon](http://docs.aws.amazon.com/cognito/latest/developerguide/amazon.html)
[Amazon Apps Console](https://sellercentral.amazon.com/gp/homepage.html/ref=xx_home_logo_home)
