### ISSUE TITLE
Update top level file comments

### ISSUE THREAD

**Issue by ryanwscott** [ExpanseLLC/lambda_authorizer#9]
Update the comments on the top of each Node.js file to the following:
- Remove created by and date
- Add License and Copyright
- Add `contributors` with appropriate names

Example: 
[License](https://github.com/Netflix/eureka/blob/master/eureka-core/src/main/java/com/netflix/eureka/EurekaBootStrap.java#L2)
[Contributors](https://github.com/Netflix/eureka/blob/master/eureka-core/src/main/java/com/netflix/eureka/EurekaBootStrap.java#L64)

**Comment by ryanwscott** [comment]
What do you think for top of files? @mle6366 @jvshank 

```
/*!
 * Expanse, LLC
 * http://expansellc.io
 *
 * Copyright 2016
 * Released under the Apache 2 license
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * @authors Meghan Erickson, James Shank
 */
```

**Comment by jvshank** [comment]
I can dig it.

**Comment by ryanwscott** [comment]
@jvshank @mle6366 I opened a PR for adding the above comment text to each .js file. If you edit a file then just make sure your name is in the author list :)
